OPTIMIZATION:
  iterations: 45000
  geometry_aware: false
  exposure_compensation: false
DENSIFICATION:
  METHOD: absolute_gradient
  FROM_ITER: 500
  UNTIL_ITER: 15000
  INTERVAL: 100
  ABS_GRAD_THRESHOLD: 0.0008
  SELECTION_MODE: threshold
  MIN_VISIBILITY_COUNT: 3
  MIN_GAUSSIAN_AGE: 200
  MAX_GAUSSIANS: 2500000
  MAX_NEW_GAUSSIANS_PER_STEP: 100000
