CAMERA: {USE_UNDISTORTED_DATA: false}
SH_SCHEDULE: {ENABLED: false}
RESOLUTION_SCHEDULE: {ENABLED: false}
DENSIFICATION:
  METHOD: hybrid
  UNIQUE_VIEW_SUPPORT_ENABLED: false
  BURST_SUPPRESSION_ENABLED: false
PRUNING: {THIN_STRUCTURE_PROTECTION: false}
EXPOSURE: {TEST_MODE: identity}
SKY: {ENABLED: false, BACKGROUND_MODE: constant}
LOW_PARALLAX: {ENABLED: false}
IMAGE_QUALITY: {SHARPNESS_AWARE_SAMPLING: false, USE_CHARBONNIER: false}
MULTIVIEW_DEPTH: {ENABLED: false}
