BASE: base.yaml
CAMERA:
  USE_UNDISTORTED_DATA: true
SKY:
  ENABLED: true
  BACKGROUND_MODE: directional_sh
LOW_PARALLAX:
  ENABLED: true
IMAGE_QUALITY:
  SHARPNESS_AWARE_SAMPLING: true
MULTIVIEW_DEPTH:
  ENABLED: true
  INTERVAL: 20
DENSIFICATION:
  MIN_UNIQUE_VIEW_BINS: 3
PRUNING:
  THIN_MIN_EDGE_SUPPORT: 0.40

