BASE: base.yaml
CAMERA:
  USE_UNDISTORTED_DATA: true
SKY:
  ENABLED: true
  BACKGROUND_MODE: directional_sh
LOW_PARALLAX:
  ENABLED: true
SH_SCHEDULE:
  MILESTONES:
    - [0, 0]
    - [3000, 1]
    - [9000, 2]
    - [16000, 3]
MULTIVIEW_DEPTH:
  ENABLED: true
  INTERVAL: 20

